# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /vildata/uzielr/Superpixels-new/Roy-CUDA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /vildata/uzielr/Superpixels-new/Roy-CUDA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /vildata/uzielr/Superpixels-new/Roy-CUDA/CMakeFiles /vildata/uzielr/Superpixels-new/Roy-CUDA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /vildata/uzielr/Superpixels-new/Roy-CUDA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Sp_demo

# Build rule for target.
Sp_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sp_demo
.PHONY : Sp_demo

# fast build rule for target.
Sp_demo/fast:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/build
.PHONY : Sp_demo/fast

#=============================================================================
# Target rules for targets named Sp_demo_for_direc

# Build rule for target.
Sp_demo_for_direc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sp_demo_for_direc
.PHONY : Sp_demo_for_direc

# fast build rule for target.
Sp_demo_for_direc/fast:
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/build
.PHONY : Sp_demo_for_direc/fast

Superpixels.o: Superpixels.cpp.o

.PHONY : Superpixels.o

# target to build an object file
Superpixels.cpp.o:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/Superpixels.cpp.o
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/Superpixels.cpp.o
.PHONY : Superpixels.cpp.o

Superpixels.i: Superpixels.cpp.i

.PHONY : Superpixels.i

# target to preprocess a source file
Superpixels.cpp.i:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/Superpixels.cpp.i
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/Superpixels.cpp.i
.PHONY : Superpixels.cpp.i

Superpixels.s: Superpixels.cpp.s

.PHONY : Superpixels.s

# target to generate assembly for a file
Superpixels.cpp.s:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/Superpixels.cpp.s
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/Superpixels.cpp.s
.PHONY : Superpixels.cpp.s

bfs_split.o: bfs_split.cpp.o

.PHONY : bfs_split.o

# target to build an object file
bfs_split.cpp.o:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/bfs_split.cpp.o
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/bfs_split.cpp.o
.PHONY : bfs_split.cpp.o

bfs_split.i: bfs_split.cpp.i

.PHONY : bfs_split.i

# target to preprocess a source file
bfs_split.cpp.i:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/bfs_split.cpp.i
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/bfs_split.cpp.i
.PHONY : bfs_split.cpp.i

bfs_split.s: bfs_split.cpp.s

.PHONY : bfs_split.s

# target to generate assembly for a file
bfs_split.cpp.s:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/bfs_split.cpp.s
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/bfs_split.cpp.s
.PHONY : bfs_split.cpp.s

demo.o: demo.cpp.o

.PHONY : demo.o

# target to build an object file
demo.cpp.o:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/demo.cpp.o
.PHONY : demo.cpp.o

demo.i: demo.cpp.i

.PHONY : demo.i

# target to preprocess a source file
demo.cpp.i:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/demo.cpp.i
.PHONY : demo.cpp.i

demo.s: demo.cpp.s

.PHONY : demo.s

# target to generate assembly for a file
demo.cpp.s:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/demo.cpp.s
.PHONY : demo.cpp.s

demo_for_direc.o: demo_for_direc.cpp.o

.PHONY : demo_for_direc.o

# target to build an object file
demo_for_direc.cpp.o:
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/demo_for_direc.cpp.o
.PHONY : demo_for_direc.cpp.o

demo_for_direc.i: demo_for_direc.cpp.i

.PHONY : demo_for_direc.i

# target to preprocess a source file
demo_for_direc.cpp.i:
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/demo_for_direc.cpp.i
.PHONY : demo_for_direc.cpp.i

demo_for_direc.s: demo_for_direc.cpp.s

.PHONY : demo_for_direc.s

# target to generate assembly for a file
demo_for_direc.cpp.s:
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/demo_for_direc.cpp.s
.PHONY : demo_for_direc.cpp.s

split_merge.o: split_merge.cpp.o

.PHONY : split_merge.o

# target to build an object file
split_merge.cpp.o:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/split_merge.cpp.o
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/split_merge.cpp.o
.PHONY : split_merge.cpp.o

split_merge.i: split_merge.cpp.i

.PHONY : split_merge.i

# target to preprocess a source file
split_merge.cpp.i:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/split_merge.cpp.i
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/split_merge.cpp.i
.PHONY : split_merge.cpp.i

split_merge.s: split_merge.cpp.s

.PHONY : split_merge.s

# target to generate assembly for a file
split_merge.cpp.s:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/split_merge.cpp.s
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/split_merge.cpp.s
.PHONY : split_merge.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/utils.cpp.o
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/utils.cpp.i
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/Sp_demo.dir/build.make CMakeFiles/Sp_demo.dir/utils.cpp.s
	$(MAKE) -f CMakeFiles/Sp_demo_for_direc.dir/build.make CMakeFiles/Sp_demo_for_direc.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Sp_demo"
	@echo "... Sp_demo_for_direc"
	@echo "... Superpixels.o"
	@echo "... Superpixels.i"
	@echo "... Superpixels.s"
	@echo "... bfs_split.o"
	@echo "... bfs_split.i"
	@echo "... bfs_split.s"
	@echo "... demo.o"
	@echo "... demo.i"
	@echo "... demo.s"
	@echo "... demo_for_direc.o"
	@echo "... demo_for_direc.i"
	@echo "... demo_for_direc.s"
	@echo "... split_merge.o"
	@echo "... split_merge.i"
	@echo "... split_merge.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

